.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH XSUNPINYIN\-PREFERENCES 1 "Oct 12, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
xsunpinyin\-preferences \-  xsunpinyin configuration tool
.SH SYNOPSIS
.B xsunpinyin\-preferences
.SH DESCRIPTION
xsunpinyin\-preferences can be used to configure xsunpinyin
.PP
To configure xsunpinyin, you can run xsunpinyin\-preferences, or right click
the xsunpinyin icon in the notification area, then select pereferences.
.SH SEE ALSO
.BR xsunpinyin (1), 
.SH AUTHOR
xsunpinyin\-preferences was written by Mike Qin <mikeandmore@gmail.com>.
.PP
This manual page was written by Liang Guo <bluestonechina@gmail.com>,
for sunpinyin project. 
